import React from "react";
import Head from "next/head";
import axios from "axios";

import VideoCard from "../components/VideoCard";
import { BASE_URL } from "../utils";
import { Video } from "../types";
import NoResults from "../components/NoResults";

interface IProps {
  videos: Video[];
}

const Home = ({ videos }: IProps) => {
  return (
    <div className="flex flex-col gap-10 videos h-full">
      <Head>
        <title>TikTik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {videos?.length ? (
        videos?.map((video: Video) => (
          <VideoCard post={video} isShowingOnHome key={video._id} />
        ))
      ) : (
        <NoResults text={`No Videos`} />
      )}
    </div>
  );
};

export default Home;

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  const { data } = await axios.get(`${BASE_URL}/api/post`);

  console.log(data);
  // let response = await axios.get(`${BASE_URL}/api/post`);

  // if (topic) {
  //   response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  // }

  return {
    props: { videos: data },
  };
};
